services:
  notifier:
    image: projectfive/notifier:latest
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
      - app
    platform: linux/x86_64
  app:
    image: projectfive/app:latest
    ports:
      - "80:80"
    volumes:
      - ./certs:/certs
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - DEBUG=${DEBUG}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - mongo
    platform: linux/x86_64
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
